### ISSUE TITLE
Custom options need to support Chinese

### ISSUE THREAD

**Issue by 0x0021** [rrva/openconnectui2#5]
Custom options need to support Chinese
<img width="516" alt="image" src="https://github.com/rrva/openconnectui2/assets/3069412/eeaf9fd5-7733-4b9e-bf39-2e7e4bdc7ff1">

**Comment by stsergo** [comment]
You can use `--config=/path/to/config` as workaround

man:
> The file should contain long-format options as would be accepted on the command line, but without the two leading -- dashes. Empty lines, or lines where the first non-space character is a # character, are ignored.

**Comment by rrva** [comment]
Please see new version 1.791 where I tried to fix this. Do not use quotes (`"`) in the arguments though.

**Comment by rrva** [comment]
@0x0021 does it work better in 1.791 ?

**Comment by 0x0021** [comment]
> 它在 1.791 中效果更好吗？

It worked, thank you very much！
